version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:6.0
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh --quiet localhost:27017/dealershipsDB || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 6


  # Node.js API service
  api:
    build: .
    container_name: node_api
    ports:
      - 3030:3030
    depends_on:
      mongo_db:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/dealershipsDB
    volumes:
      - .:/app
    command: ["sh", "-c", "sleep 5 && node app.js"]

volumes:
  mongo_data: {}
